# Uncomment the next line to define a global platform for your project
# platform :macos, '10.14'

target 'MacBulb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MacBulb
  pod 'Swifter'
end
